# Assignment 1: Numpy

Perform the follwing tasks:


In [10]:
#3.1: import the numpy library
import numpy as np

In [11]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.92129588, 0.43840358, 0.3455333 , 0.46770398, 0.26351971,
        0.86843783, 0.91029785, 0.94573446, 0.0513901 , 0.45025094],
       [0.37981699, 0.01597341, 0.91163979, 0.8203728 , 0.87472962,
        0.48323605, 0.32593322, 0.81720552, 0.13732076, 0.91737637],
       [0.11855286, 0.06557147, 0.00243616, 0.29383233, 0.11595177,
        0.94532279, 0.08312836, 0.86439301, 0.97263829, 0.5421843 ],
       [0.06303265, 0.7397074 , 0.12518153, 0.42608459, 0.51384261,
        0.7340645 , 0.62750601, 0.79192831, 0.12727913, 0.87343244],
       [0.16525177, 0.26571009, 0.88138252, 0.0739635 , 0.96963019,
        0.13406776, 0.36033126, 0.01110142, 0.03435336, 0.01284614],
       [0.72238473, 0.61659838, 0.80081629, 0.04001238, 0.17312132,
        0.39508499, 0.58691403, 0.30303234, 0.6984733 , 0.69058415],
       [0.32056449, 0.65414928, 0.85535765, 0.67890624, 0.53967343,
        0.95013408, 0.25321444, 0.41973103, 0.24427665, 0.43016103],
       [0.0407567 , 0.32967715, 0.1592761

In [12]:
#3.3: return only the odd rows of A
A[1::2,]

#Return only 
#[1], [3], [5], etc...
#and not
#[0], [2], [4], etc...

array([[0.37981699, 0.01597341, 0.91163979, 0.8203728 , 0.87472962,
        0.48323605, 0.32593322, 0.81720552, 0.13732076, 0.91737637],
       [0.06303265, 0.7397074 , 0.12518153, 0.42608459, 0.51384261,
        0.7340645 , 0.62750601, 0.79192831, 0.12727913, 0.87343244],
       [0.72238473, 0.61659838, 0.80081629, 0.04001238, 0.17312132,
        0.39508499, 0.58691403, 0.30303234, 0.6984733 , 0.69058415],
       [0.0407567 , 0.32967715, 0.15927614, 0.06941491, 0.29024473,
        0.84172351, 0.76615336, 0.35213941, 0.22471169, 0.65245187],
       [0.50479639, 0.81033008, 0.69752865, 0.75963096, 0.40435719,
        0.96763776, 0.56451267, 0.58659946, 0.99237453, 0.05291263]])

In [13]:
#3.4: perform a matrix multiplication of A with it's transposed
np.dot(A,A.T)

array([[4.13117367, 3.19545136, 2.3150078 , 3.11777091, 1.32587742,
        2.78768477, 2.99623326, 2.41282436, 3.61384928, 3.50697376],
       [3.19545136, 4.28177744, 2.21202077, 2.97406256, 1.9871596 ,
        2.55783285, 3.25384781, 2.05041814, 3.77586929, 3.13323026],
       [2.3150078 , 2.21202077, 3.00585243, 2.2690464 , 0.37998987,
        1.89785046, 2.09790649, 1.81697668, 2.59564931, 2.84738832],
       [3.11777091, 2.97406256, 2.2690464 , 3.35124201, 1.19595744,
        2.2982589 , 2.77329684, 2.42107688, 3.00399069, 2.95159903],
       [1.32587742, 1.9871596 , 0.37998987, 1.19595744, 1.96967964,
        1.46054232, 1.79138378, 0.93020841, 1.74617712, 1.73620663],
       [2.78768477, 2.55783285, 1.89785046, 2.2982589 , 1.46054232,
        3.13207222, 2.55937025, 1.9097525 , 3.02102243, 3.14436113],
       [2.99623326, 3.25384781, 2.09790649, 2.77329684, 1.79138378,
        2.55937025, 3.40222672, 2.04583117, 3.37003286, 3.59618937],
       [2.41282436, 2.05041814, 1.8169766

In [14]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[ 1.29515072, -4.60489732,  2.58215378,  1.6092067 ,  2.46038656,
         0.59753475,  2.67582053, -4.18116696,  3.83018208, -4.9637915 ],
       [-0.14387988, -0.62103006, -0.24791017,  1.10668058,  0.02929624,
         0.33949013,  0.35751987, -0.79487914, -0.1282712 ,  0.13282508],
       [-0.70384429,  4.97479997, -2.72953697, -2.63998657, -2.50911058,
         0.12174118, -2.15415711,  3.97615765, -4.18009461,  4.80770457],
       [-0.18344397, -0.68947584, -0.03270761,  0.63999459, -0.1531945 ,
        -0.40228702,  0.67300104, -1.05402226,  1.51733292, -0.60538012],
       [ 0.49214467, -4.03705681,  2.55982494,  2.12982826,  3.18588015,
        -0.15894752,  1.89342633, -3.49014245,  3.41396028, -4.22196006],
       [ 0.39371612, -1.42143242,  1.00043924, -0.27495704,  0.57696881,
        -0.33328354,  1.68034965, -0.07075791,  0.76966996, -1.47023914],
       [-0.15450193,  1.91962075, -1.62909032, -0.88088871, -0.99454074,
        -0.23173947, -2.00810029,  2.43309731

In [15]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
np.where(A > 0.5, A/2, A)

array([[0.46064794, 0.43840358, 0.3455333 , 0.46770398, 0.26351971,
        0.43421892, 0.45514892, 0.47286723, 0.0513901 , 0.45025094],
       [0.37981699, 0.01597341, 0.4558199 , 0.4101864 , 0.43736481,
        0.48323605, 0.32593322, 0.40860276, 0.13732076, 0.45868819],
       [0.11855286, 0.06557147, 0.00243616, 0.29383233, 0.11595177,
        0.4726614 , 0.08312836, 0.43219651, 0.48631915, 0.27109215],
       [0.06303265, 0.3698537 , 0.12518153, 0.42608459, 0.25692131,
        0.36703225, 0.31375301, 0.39596415, 0.12727913, 0.43671622],
       [0.16525177, 0.26571009, 0.44069126, 0.0739635 , 0.48481509,
        0.13406776, 0.36033126, 0.01110142, 0.03435336, 0.01284614],
       [0.36119236, 0.30829919, 0.40040814, 0.04001238, 0.17312132,
        0.39508499, 0.29345701, 0.30303234, 0.34923665, 0.34529208],
       [0.32056449, 0.32707464, 0.42767882, 0.33945312, 0.26983672,
        0.47506704, 0.25321444, 0.41973103, 0.24427665, 0.43016103],
       [0.0407567 , 0.32967715, 0.1592761